### ISSUE TITLE
Need to add karma-chrome-launcher dependency

### ISSUE THREAD

**Issue by leighsn** [learn-co-curriculum/angular-testing-controllers-readme#2]
Running karma tests also requires installing the karma chrome launcher:

npm install karma-chrome-launcher --save-dev

Suggest adding this to the list of npm installations

**Comment by ipc103** [comment]
Hey Leigh,

The karma-chrome-launcher dependences is actually listed in the `package.json` - did it not install properly for you?

Ian

**Comment by NStephenson** [comment]
I also had to do the same
